### ISSUE TITLE
Cannot force the Lua version to use at build time

### ISSUE THREAD

**Issue by Peuc** [markand/irccd#13]
Irccd cannot be build when 5.2 and 5.3 versions of Lua are available on the system. The cmake checks the 5.2 version is available, as expected, but uses the latest version when compiling. Since irccd isn't compatible with Lua 5.3, it prevents compilation on most up to date Linux distributions.

We need additional cmake parameters to force the Lua version to use at build time. After some checks, I found a working example with the solarus project ( https://github.com/christopho/solarus ). It uses two additional variables named `LUA_INCLUDE_DIR` and `LUA_LIBRARY`.

**Comment by markand** [comment]
Yes, anyway the preferred way is to import Lua directly in the source tree to compile as C++. I will do that for Lua 5.2 and optionally search for LuaJIT as system-wide library.
